name: gof_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pygame
  - pandas
  - numba
  - jupyterlab
  - notebook
  - tqdm
  - h5py
  - seaborn
  - scikit-image
  - networkx
  - pytest
